### ISSUE TITLE
Keeping whitespaces?

### ISSUE THREAD

**Issue by ggaemo** [ischlag/TP-Transformer#2]
Thank you for your great work!

I was reading through your code after I read the paper, and noticed that the white spaces were kept instead of being ignored.

Does keeping white spaces improve performance?

As far as I know, white spaces are not used in Transformers in NLP.

**Comment by ischlag** [comment]
Hi,

The mathematics dataset is a sequence to sequence problem. For this type of data, the sequences are naturally modelled on a character level and as such incorporate also a whitespace symbol similar to character-level language models. We did not experiment with a word-level-like tokenization or with any changes to the data such as removing whitespaces.
