### ISSUE TITLE
License

### ISSUE THREAD

**Issue by tommccoy1** [ischlag/TP-Transformer#4]
Thank you for the clear work and easy-to-use code! Would you be able to add a license to the GitHub repo? I would like to use the code defining the TP-Transformer architecture (as long as the license permits), but I don't think I can use it unless the repo has a license that permits such usage.

(Directions for adding a license here: https://docs.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository)

**Comment by ischlag** [comment]
Hi Tom, certainly. I think the MIT license will do.

**Comment by tommccoy1** [comment]
Yes, that's perfect - thank you!
