### ISSUE TITLE
LSTM baseline

### ISSUE THREAD

**Issue by harryjhnam** [ischlag/TP-Transformer#6]
Hi! 
It was a very interesting paper!
So I tried to improve the performance of  Simple and Attentional LSTM for the data set,
but there was no baseline code implemented.
I've tried to reproduce the performance, but I keep failing...
I am wondering if you can share the code you implemented for LSTM baselines.
It will be a great help for my project. 
Thanks!

**Comment by ischlag** [comment]
Thank you for your interest in our work. We didn't run LSTM baselines and have none implemented. The LSTM baselines that we report are from _Analysing Mathematical Reasoning Abilities of Neural Models_ by Saxton et al.  Unfortunately, they did not share public code. 

An important "trick" to make LSTMs work better, is to introduce 16 "thinking steps" between the encoder and decoder. See section 4.2 of the paper above.
